[infculti]
MARCAINF = {type = 'bool', length = 1}
CODFIN = {type = 'Int64', length = 4}
CODLOTE = {type = 'Int64', length = 4}
NOMLOTE = {type = 'string', length = 20}
ANO = {type = 'Int64', length = 4}
SEMESTRE = {type = 'Int64', length = 1}
CODCULTIVO = {type = 'Int64', length = 2}
CULTIVO = {type = 'string', length = 7}
SISTEMA = {type = 'Int64', length = 1}
TONELADAS = {type = 'float', length = 12}
ASISTEC = {type = 'Int64', length = 7}
ARRHEC = {type = 'Int64', length = 10}
ARREND = {type = 'Int64', length = 1}
COSTOTSC = {type = 'float', length = 16}
INGTSC = {type = 'Int64', length = 12}
TIRSC = {type = 'float', length = 16}
TIRCC = {type = 'float', length = 16}
VPNSC = {type = 'float', length = 16}
RBCSC = {type = 'float', length = 16}
COSTOTCC = {type = 'float', length = 16}
INGTCC = {type = 'Int64', length = 12}
VPNCC = {type = 'float', length = 16}
RBCCC = {type = 'float', length = 16}
ASISTENCIA = {type = 'float', length = 6}
ARRIENDO = {type = 'float', length = 6}
PREPAR = {type = 'float', length = 6}
SIEMBRA = {type = 'float', length = 6}
SEMILLA = {type = 'float', length = 6}
LABSIEM = {type = 'float', length = 6}
RIEGO = {type = 'float', length = 6}
AGUA = {type = 'float', length = 6}
MMTO = {type = 'float', length = 6}
FERTIL = {type = 'float', length = 6}
INSFERT = {type = 'float', length = 6}
APFERT = {type = 'float', length = 6}
MALEZAS = {type = 'float', length = 6}
HERBIC = {type = 'float', length = 6}
APHERB = {type = 'float', length = 6}
MANHERB = {type = 'float', length = 6}
PLAGAS = {type = 'float', length = 6}
INSECT = {type = 'float', length = 6}
APINSECT = {type = 'float', length = 6}
MANINSECT = {type = 'float', length = 6}
ENFERM = {type = 'float', length = 6}
FUNGIC = {type = 'float', length = 6}
APFUNGIC = {type = 'float', length = 6}
TOTINS = {type = 'float', length = 6}
INSUMOS = {type = 'float', length = 6}
APINSUM = {type = 'float', length = 6}
RECOLEC = {type = 'float', length = 6}
TRANSPORTE = {type = 'float', length = 6}
VARIOS = {type = 'float', length = 6}
SUBTOTAL = {type = 'float', length = 6}
ADMON = {type = 'float', length = 6}
INTERESES = {type = 'float', length = 6}
IMPUESTOS = {type = 'float', length = 6}
TOTALES = {type = 'float', length = 6}
COSTOCONTA = {type = 'Int64', length = 12}
NUMCONTROL = {type = 'Int64', length = 8}
CODCC = {type = 'string', length = 8}
COFINCA = {type = 'string', length = 5}


[insaplica]
CODINSAP = {type = 'Int64', length = 10}
NUMCONTROL = {type = 'Int64', length = 4}
CODAPLIC = {type = 'string', length = 8}
CODTIPO = {type = 'Int64', length = 4}
NOMTIPO = {type = 'string', length = 14}
CODINSUM = {type = 'Int64', length = 4}
NOMINSUMO = {type = 'string', length = 15}
CODUNID = {type = 'Int64', length = 4}
NOMUNID = {type = 'string', length = 11}
CANTAPLIC = {type = 'float', length = 14}
EQUIVALE = {type = 'float', length = 8}
CANTOTAL = {type = 'float', length = 14}
FORMA1 = {type = 'Int64', length = 1}
MARCAINAP = {type = 'string', length = 1}
PESO = {type = 'float', length = 8}
PRECIO = {type = 'float', length = 14}
FECHAPLI = {type = 'datetime64[s]', length = 8}
FECHAGER = {type = 'datetime64[s]', length = 8}
FECHA1 = {type = 'datetime64[s]', length = 8}
CODCP = {type = 'Int64', length = 4}
COFINCA = {type = 'string', length = 5}


[labor]
CODLABOR = {type = 'Int64', length = 4}
NOMLABOR = {type = 'string', length = 30}
ARROZ = {type = 'bool', length = 1}
SORGO = {type = 'bool', length = 1}
SOYA = {type = 'bool', length = 1}
MAIZ = {type = 'bool', length = 1}
ALGODON = {type = 'bool', length = 1}
FORMLABOR = {type = 'Int64', length = 1}
MARCALAB = {type = 'bool', length = 1}
CODCOSTO = {type = 'string', length = 40}


[Cultivo]
CODCULTIVO = {type = 'Int64', length = 3}
NOMCULTIVO = {type = 'string', length = 7}
MARCACUL = {type = 'bool', length = 1}
COSCUL = {type = 'string', length = 10}
NAT1 = {type = 'string', length = 9}
COSVEN = {type = 'string', length = 10}
NAT2 = {type = 'string', length = 9}
INGVEN = {type = 'string', length = 10}
NAT3 = {type = 'string', length = 9}
GUIA1 = {type = 'string', length = 4}
GUIA2 = {type = 'string', length = 4}
GUIA3 = {type = 'string', length = 4}
SALICULT = {type = 'string', length = 10}
NAT4 = {type = 'string', length = 9}


[municips]
COD_SEC = {type = 'Int64', length = 7}
SECCIONAL = {type = 'string', length = 13}
CODDEP = {type = 'string', length = 2}
NOMDEP = {type = 'string', length = 18}
CODMUNI = {type = 'string', length = 5}
NOMMUNI = {type = 'string', length = 26}
ZONA = {type = 'string', length = 13}


[concepto]
COD_ACTI = {type = 'string', length = 1}
ACTIVIDAD = {type = 'string', length = 25}


[jorculti]
NUMCONTROL = {type = 'Int64', length = 8}
CODLABOR = {type = 'Int64', length = 4}
FECHALAB = {type = 'datetime64[s]', length = 8}
CANTJORN = {type = 'float', length = 8}
CUNITJORN = {type = 'float', length = 8}
CODEMPL = {type = 'Int64', length = 4}
NOMEMIP = {type = 'string', length = 30}
CODPROV = {type = 'Int64', length = 4}
HORASEMP = {type = 'string', length = 6}
COSTOTAL = {type = 'float', length = 12}
FORMAJOR = {type = 'Int64', length = 1}
ACCION = {type = 'Int64', length = 1}
MARCAJORN = {type = 'bool', length = 1}
NOMLABOR = {type = 'string', length = 30}
CODAPLICA = {type = 'string', length = 8}
OBSERVA = {type = 'string', length = 30}
VAPAGO = {type = 'Int64', length = 10}
NUM_FECHA = {type = 'Int64', length = 8}
CODCP = {type = 'Int64', length = 8}
COFINCA = {type = 'string', length = 5}


[insumonal]
SORTBY = {type = 'Int64', length = 5}
TIPO_INS = {type = 'Int64', length = 1}
NOMBRE = {type = 'string', length = 20}
CODTIPNAL = {type = 'Int64', length = 2}
CODINSUM = {type = 'Int64', length = 4}
NOMBREINS = {type = 'string', length = 30}
UNIDAD = {type = 'string', length = 3}
CODUNIDAD = {type = 'Int64', length = 1}
NITROGENO = {type = 'float', length = 9}
FOSFORO = {type = 'float', length = 9}
POTASIO = {type = 'float', length = 9}
OTROS = {type = 'float', length = 9}
ING_ACTIVO = {type = 'float', length = 17}
IACTIVO = {type = 'string', length = 51}
C_COMERCIA = {type = 'string', length = 20}
S = {type = 'float', length = 9}
MG = {type = 'float', length = 9}
CA = {type = 'float', length = 9}
ZN = {type = 'float', length = 9}
FE = {type = 'float', length = 9}
MN = {type = 'float', length = 9}
CU = {type = 'float', length = 9}
CL = {type = 'float', length = 9}
B = {type = 'float', length = 9}
SI = {type = 'float', length = 9}
MO = {type = 'float', length = 9}


[lotesfin]
CODFIN = {type = 'Int64', length = 4}
CODLOTE = {type = 'Int64', length = 4}
NOMLOTE = {type = 'string', length = 20}
AREA = {type = 'float', length = 8}
ARREND = {type = 'Int64', length = 1}
COSARRTOT = {type = 'Int64', length = 10}
COSARRHEC = {type = 'Int64', length = 10}
VALCOMTOT = {type = 'Int64', length = 10}
VALCOMHEC = {type = 'Int64', length = 10}
CONTLOTE = {type = 'Int64', length = 4}
MARCALOTE = {type = 'bool', length = 1}
CULTI = {type = 'string', length = 7}
CODCC = {type = 'string', length = 8}
COFINCA = {type = 'string', length = 5}
FINCA = {type = 'Int64', length = 1}
_NullFlags = {type = 'null', length = 1}


[ubica]
CODFIN = {type = 'Int64', length = 4}
NOMFIN = {type = 'string', length = 20}
PAIS = {type = 'string', length = 10}
DEPARTAM = {type = 'string', length = 14}
MUNICIPIO = {type = 'string', length = 17}
PROPIETA = {type = 'string', length = 30}
ESTACIONM = {type = 'string', length = 30}
MARCAFIN = {type = 'bool', length = 1}
CODCC = {type = 'string', length = 8}
COFINCA = {type = 'string', length = 5}
CODMUNI = {type = 'string', length = 5}
AGRONOMO = {type = 'string', length = 30}
ARRENDATAR = {type = 'string', length = 30}
TENENCIA = {type = 'Int64', length = 1}
VEREDA = {type = 'string', length = 25}
_NullFlags = {type = 'null', length = 1}


[labculti]
NUMCONTROL = {type = 'Int64', length = 8}
CODLABOR = {type = 'Int64', length = 4}
NOMLABOR = {type = 'string', length = 30}
VALUNICO = {type = 'float', length = 14}
CANTPASES = {type = 'float', length = 11}
FECHALAB = {type = 'datetime64[s]', length = 8}
FORMALAB = {type = 'Int64', length = 1}
CODPROV = {type = 'Int64', length = 3}
PESOBULTO = {type = 'float', length = 11}
TARIFA = {type = 'Int64', length = 2}
OPCION = {type = 'Int64', length = 1}
OPCMAN = {type = 'Int64', length = 1}
HECTAREA = {type = 'float', length = 8}
COSTOTAL = {type = 'Int64', length = 10}
VAPAGO = {type = 'Int64', length = 10}
NUM_FECHA = {type = 'Int64', length = 8}
MARCA = {type = 'bool', length = 1}
NOMEMPL = {type = 'string', length = 30}
CODAPLICA = {type = 'string', length = 8}
OBSERVA = {type = 'string', length = 30}
FIJO = {type = 'Int64', length = 1}
CODCP = {type = 'Int64', length = 8}
COFINCA = {type = 'string', length = 5}


[fincas]
ANO = {type = 'string', length = 4}
ZONA = {type = 'string', length = 10}
COFINCA = {type = 'string', length = 7}
CODDEPTO = {type = 'string', length = 2}
NOMDEPTO = {type = 'string', length = 9}
CODMUNI = {type = 'string', length = 5}
NOMUNICI = {type = 'string', length = 25}
VEREDA = {type = 'string', length = 25}
NOMPROPIE = {type = 'string', length = 35}


[Undcomp]
CODUNIDAD = {type = 'Int64', length = 2}
CODIGO = {type = 'Int64', length = 2}
NOMBREUND = {type = 'string', length = 10}
EQUIVALE = {type = 'float', length = 8}


[Invimpr]
MARCAINV = {type = 'bool', length = 1}
TIPINSUMO = {type = 'string', length = 14}
CODTIPO = {type = 'Int64', length = 4}


