[paths]
raw_data_path = "path/to/zip/files/with/dbfs"
data_path = "/path/to/folder/with/dbfs/files"
# The folder structure is as follows:
# raw_data_path
# ├── backup_batch
# │   └── user_backup_folder
#         └── .dbf files
[dbfs-pars]
dbfs_folders = [
    # Folders that contain each DBF backup batch
]
dbfs_tables = [ 
    # Name of DBFs tables were need. Do not include extension, only name. 
    # Any table that starts with the name here included is included. For example
    # If dbfs_tables = ["fincas"], then any table that starts with "fincas" is 
    # included.
    "table_1", "table_2", "table_3"
]

# With the tables defined in dbfs_tables, we will create new tables. The new tables
# are defined next. There is a base table, which is the table where the created 
# will be built in top of. There are join tables, that will be joined in a given
# column. An index is created by hex-encoding the string resulting from concatenating
# the columns given in idx.

[[table]] # Each table to generate
name = "Table A" # Name of the table. Not necesarilly in dbfs_tables
# Index of the table (optional) If no index, then sequential will be considered.
idx = ["col1", "col2"]
mandatory = true # IF this table is missing, the backup is not processed
    [table.base] # The base table to use
        name = "table_1" # from dbf_tables
        columns = [
            "col1", "col2", "col_3" 
        ]
    [[table.join]] # The tables to be joined to this table
        name = "table_2"
        idx = "col1" # Join table_2 by mapping col1 in table_2 to col2 in table_1
        on = "col2"
        columns = [ # Columns to include
            "col1", "col2", "col3"
        ]
        column_keyerror_catch = ["col3"] # A column we can miss. i.e., if that column from columns is missing, it's ok
    [[table.link]] # Tables to connect to this one. Indexes from those tables will be added as columns
        link = 'TableB'
        from = ["coln"]
        to = ["coln"]
    [[table.cleaning]] # Define the cleaning pipeline as a list of functions and kwargs
        function = 'string_homogenization'

[[table]]
name = "Table B"
mandatory = false
idx = ["col"]
    [table.base]
        name = ""
        columns = [
        ]
    [[table.join]]
        name = ""
        idx = ""
        on = ""
        columns = [""]
    [[table.link]]
        link = 'TableB'
        from = ["coln"]
        to = ["coln"]
    [[table.cleaning]]
        function = 'string_homogenization'

[control]
skip_backups = [
    # Prefixes of backups to skip
]